---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: economic efficiency faq, bluexp, lifecycle planning frequently asked questions 
summary: 'Le service de planification du cycle de vie NetApp identifie les clusters présentant une faible capacité actuelle ou prévue et vous fournit des recommandations sur la hiérarchisation des données ou la capacité supplémentaire (pour les systèmes AFF ).  Le service fournit également des recommandations de mise à jour technologique sur les systèmes qui approchent de la fin de vie.' 
---
= Quoi de neuf dans la planification du cycle de vie
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Découvrez les nouveautés en matière de planification du cycle de vie.



== 06 octobre 2025



=== BlueXP economic efficiency est désormais une planification du cycle de vie

BlueXP economic efficiency a été renommée Planification du cycle de vie.

Vous pouvez y accéder à partir de la barre de navigation de gauche de la console NetApp en sélectionnant *Stockage* > *Planification du cycle de vie*.



=== BlueXP est désormais NetApp Console

La console NetApp , construite sur la base BlueXP améliorée et restructurée, fournit une gestion centralisée du stockage NetApp et des services de données NetApp dans les environnements sur site et cloud à l'échelle de l'entreprise, offrant des informations en temps réel, des flux de travail plus rapides et une administration simplifiée, hautement sécurisée et conforme.

Pour plus de détails sur ce qui a changé, consultez lelink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Notes de version de la console NetApp"] .



== 15 mai 2024



=== Fonctionnalités désactivées

Certaines fonctionnalités BlueXP economic efficiency ont été temporairement désactivées :

* Actualisation technologique
* Augmenter la capacité




== 14 mars 2024



=== Options de mise à jour technologique

Si vous disposez d'actifs existants et souhaitez déterminer si une technologie doit être mise à jour, vous pouvez utiliser les options d'actualisation de la technologie d'efficacité économique BlueXP .  Vous pouvez soit consulter une brève évaluation de vos charges de travail actuelles et obtenir des recommandations, soit, si vous avez envoyé des journaux AutoSupport à NetApp au cours des 90 derniers jours, le service peut désormais fournir une simulation de charge de travail pour voir comment vos charges de travail fonctionnent sur du nouveau matériel.

Vous pouvez également ajouter une charge de travail et exclure les charges de travail existantes de la simulation.

Auparavant, vous pouviez uniquement évaluer vos actifs et déterminer si une mise à jour technologique était recommandée.

La fonctionnalité fait désormais partie de l’option Actualisation technologique dans la navigation de gauche.

En savoir plus sur le https://docs.netapp.com/us-en/bluexp-economic-efficiency/use/tech-refresh.html["Évaluer une mise à jour technologique"] .



== 08 novembre 2023



=== Actualisation technologique

Cette version de BlueXP economic efficiency inclut une nouvelle option permettant d’évaluer vos actifs et d’identifier si une actualisation technologique est recommandée.  BlueXP economic efficiency comprend une nouvelle option d'actualisation technologique dans la navigation de gauche, de nouvelles pages où vous pouvez évaluer vos charges de travail et vos actifs actuels, ainsi qu'un rapport qui vous fournit des recommandations.



== 02 avril 2023



=== Présentation de BlueXP economic efficiency

La nouvelle BlueXP economic efficiency identifie les actifs de stockage avec une faible capacité actuelle ou prévue et fournit des recommandations sur la hiérarchisation des données ou la capacité supplémentaire pour les systèmes AFF sur site.

link:https://docs.netapp.com/us-en/bluexp-economic-efficiency/get-started/intro.html["En savoir plus sur l'efficacité économique de NetApp"] .
